const lang = {

    zh: {
        title: "打造 NVIDIA 頂級生態系，校園夜間的終極守護者",
        subtitle: "這不僅是一台智慧無人巡檢載具，更是結合 NVIDIA 頂尖技術、雲端伺服器、數位孿生與邊緣運算的 <strong>智慧移動大腦</strong>。",
        video_title: "系統展示影片" ,
        video_desc: "由國立中興大學 (NCHU) 與國立勤益科技大學 (NCUT) 跨校強強聯手，我們正重新定義校園安全與無人化管理。<br>透過建構極致的 NVIDIA 軟硬體生態系，我們讓機器具備了感知、決策與行動的能力，成為守護校園每個角落的最強後盾。",
        key_features : "核心亮點",
        feat1_title : "校園夜間的守護者",
        feat1_desc : "突破傳統影像與極端天候的物理限制。全天候 24 小時精準辨識並主動警示潛在威脅，消除校園安全盲區。",
        feat2_title : "全方位智駕與任務派遣",
        feat2_desc : "具備強大的智慧自主導航能力，同時支援低延遲的遠端遙控與即時任務指派，實現人機協作的無縫接軌。",
        feat3_title : "NVIDIA 全生態系驅動",
        feat3_desc : "從邊緣運算到虛擬模擬，深度整合 NVIDIA 頂級技術，涵蓋 Omniverse 數位孿生、Isaac 機器人控制與 Alpamayo 邊緣推論。",
        feat4_title : "MSI 企業級算力加值",
        feat4_desc : "系統後端搭載微星科技 (MSI) 強悍的 MGX 與 DGX 伺服器 (Powered by MSI)，為龐大的多模態感測數據與 AI 模型，提供強大且高效的極致算力支援。",
        team_title : "核心團隊",
        exp_title : "專案負責項目與技術專長",
        contact_person : " 聯絡人",
        pi_name : "王國禎 特聘教授",
        pi_title : "國立中興大學 機械工程學系 特聘教授 ｜ 計畫總主持人",
        pi_edu : "美國加州大學洛杉磯分校 機械工程 博士",
        pi_exp_1 : "數位孿生與模擬",
        pi_exp_2 : "3D高斯散射",
        pi_exp_3 : "機器人控制",
        pi_exp_4 : "AI 邊緣推論",
        pi_exp_5 : "遠端控制",
        copi_1_name : "邱顯俊 副教授",
        copi_1_title : "國立中興大學 機械工程學系 副教授 ｜ 專案共同主持人",
        copi_1_edu : "美國密西根大學 機械工程 博士",
        copi_1_exp_1 : "全天候熱影像感知",
        copi_1_exp_2 : "高精度空間建圖",
        copi_1_exp_3 : "多模態視覺融合",
        copi_1_exp_4 : "精準定位導航",
        copi_2_name : "林正堅 講座教授",
        copi_2_title : "國立勤益科大 講座教授兼教務長 ｜ 專案共同主持人",
        copi_2_edu : "國立交通大學 電機與控制工程研究所 博士",
        copi_2_exp_1 : "光達感知",
        copi_2_exp_2 : "環境辨識",
        copi_2_exp_3 : "多模態融合",
        copi_2_exp_4 : "自主導航",
        pm_1_name : "曾凱傑",
        pm_1_title : "國立中興大學 資訊管理學系 碩士 ｜ 專案經理",
        pm_1_edu : "國立中興大學 資訊管理學系 碩士",
        pm_1_exp_1 : "全端系統架構 ",
        pm_1_exp_2 : "專案管理與領導",
        pm_1_exp_3 : "對外資源橋樑",
        pm_1_exp_4 : "AI 感知生態系",
        member_title : "團隊成員",
        member_1_name : "李哲瑋",
        member_1_title : " ",
        member_2_name : "許庭瑜",
        member_2_title : " ",
        member_3_name : "柳孟儇",
        member_3_title : " ",
        member_4_name : "林書任",
        member_4_title : " ",
        member_5_name : "何苡琳",
        member_5_title : " ",
        member_6_name : "李唐鼎",
        member_6_title : " ",
        member_7_name : "陳柄宏",
        member_7_title : " ",
        member_8_name : "曾益宏",
        member_8_title : " ",
        member_9_name : "林學謙",
        member_9_title : " ",
        member_10_name : "張潤堂",
        member_10_title : " ",
        member_11_name : "韓孟潔",
        member_11_title : " ",
        member_12_name : "呂哲文",
        member_12_title : " ",
        member_13_name : "黃鼎翔",
        member_13_title : " ",

    },

    en: {
        title: "Building a Premier NVIDIA Ecosystem—The Ultimate Nighttime Guardian of the Campus",
        subtitle: "This is not merely a smart unmanned inspection vehicle; it is an <strong>Intelligent Mobility Brain</strong> that integrates cutting-edge NVIDIA technologies, cloud servers, digital twins, and edge computing.",
        video_title: "System Demonstration" ,
        video_desc: "Through a powerful cross-institutional alliance between National Chung Hsing University (NCHU) and National Chin-Yi University of Technology (NCUT), we are redefining campus security and unmanned management. <br>By building the ultimate NVIDIA hardware and software ecosystem, we empower the machine with advanced perception, decision-making, and execution capabilities, making it the strongest backbone for safeguarding every corner of the campus.",
        key_features : "Key Features",
        feat1_title : "The Nighttime Guardian",
        feat1_desc : "Breaking through the physical limitations of traditional imaging and extreme weather. It provides 24/7 precise recognition and proactively alerts against potential threats, eliminating campus security blind spots.",
        feat2_title : "Comprehensive Autonomous Driving & Task Dispatch",
        feat2_desc : "Equipped with robust smart autonomous navigation capabilities while perfectly supporting low-latency remote control and real-time task dispatch, achieving seamless human-machine collaboration.",
        feat3_title : "Driven by the Full NVIDIA Ecosystem",
        feat3_desc : "Deeply integrating top-tier NVIDIA technologies from edge computing to virtual simulation, covering Omniverse Digital Twins, Isaac Robotics Control, and Alpamayo Edge Inference.",
        feat4_title : "Empowered by MSI Enterprise-Grade Computing",
        feat4_desc : "The backend system is equipped with robust MSI MGX and DGX servers (Powered by MSI), providing powerful, highly efficient, and ultimate computing support for massive multi-modal sensor data and AI models.",
        team_title : "Faculty & Principal Investigators",
        exp_title : "Responsibilities & Expertise",
        contact_person : " Contact Person",
        pi_name : "Distinguished Prof. Gou-Jen Wang",
        pi_title : "Distinguished Professor, Dept. of Mechanical Engineering, NCHU | Principal Investigator",
        pi_edu : "Ph.D. in Mechanical Engineering, University of California, Los Angeles (UCLA)",
        pi_exp_1 : "Digital Twin & Simulation",
        pi_exp_2 : "3D Gaussian Splatting",
        pi_exp_3 : "Robotics Control",
        pi_exp_4 : "AI Edge Inference",
        pi_exp_5 : "Remote Control",
        copi_1_name : "Assoc. Prof. Shean-Juinn Chiou",
        copi_1_title : " Associate Professor, Dept. of Mechanical Engineering, NCHU | Co-Principal Investigator",
        copi_1_edu : "Ph.D. in Mechanical Engineering, University of Michigan",
        copi_1_exp_1 : "All-Weather Thermal Perception",
        copi_1_exp_2 : "High-Precision Spatial Mapping",
        copi_1_exp_3 : "Multi-Modal Visual Fusion",
        copi_1_exp_4 : "Precision Localization & Navigation",
        copi_2_name : "Chair Prof. Cheng-Jian Lin",
        copi_2_title : "Chair Professor & Dean of Academic Affairs, NCUT | Co-Principal Investigator",
        copi_2_edu : "Ph.D., Institute of Electrical and Control Engineering, National Chiao Tung University (NCTU)",
        copi_2_exp_1 : "LiDAR Perception",
        copi_2_exp_2 : "Environment Recognition",
        copi_2_exp_3 : "Multi-Modal Fusion",
        copi_2_exp_4 : "Autonomous Navigation",
        pm_1_name : "Kai-Jie Tseng",
        pm_1_title : "M.S., Dept. of Management Information Systems, NCHU | Project Manager, NCHU Guardian",
        pm_1_edu : "M.S. in Management Information Systems, National Chung Hsing University (NCHU)",
        pm_1_exp_1 : "Full-Stack System Architecture",
        pm_1_exp_2 : "Project Management & Leadership",
        pm_1_exp_3 : "External Resource Liaison",
        pm_1_exp_4 : "AI Perception Ecosystem",
        member_title : "Team Member",
        member_1_name : "LI,ZHE-WEI",
        member_1_title : " ",
        member_2_name : "HSU TING-YU",
        member_2_title : " ",
        member_3_name : "Liu,Meng-Hsuan",
        member_3_title : " ",
        member_4_name : "LIN, SHU-JEN",
        member_4_title : " ",
        member_5_name : "Ho,Yi-Lin",
        member_5_title : " ",
        member_6_name : "LI TANG DING",
        member_6_title : " ",
        member_7_name : "Chen Bing Hong",
        member_7_title : " ",
        member_8_name : "ZENG,YI-HONG",
        member_8_title : " ",
        member_9_name : "LIN XUE-QIAN",
        member_9_title : " ",
        member_10_name : "CHANG-JUN-TANG",
        member_10_title : " ",
        member_11_name : "Meng Chieh, Han",
        member_11_title : " ",
        member_12_name : "LU CHE WEN",
        member_12_title : " ",
        member_13_name : "HUANG,TING-HSIANG",
        member_13_title : " ",
    }

};
